version: '3'

services:
  nginx1:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www/:/var/www/
      - ./nginx1/default.conf:/etc/nginx/conf.d/default.conf

  php1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/
    depends_on:
      - db
    ports:
      - "9001:9000"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: